# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('URLInspectorApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlitem',
            old_name='full_url',
            new_name='absolute_url',
        ),
    ]
